S1 us06
WildCodeSchool-2023-09/php-paris-p3-originsdigital pull request #10
Opened 2024-01-11 14:37 UTC by ElieBendier

I have finished my US that includes :
- Index languages
- Category languages
- Video languages

Responsive.

2024-01-11 14:56 UTC, NicoDestephen approved these changes

2024-01-11 20:25 UTC, mickaellambert requested changes

2024-01-11 20:25 UTC, mickaellambert commented on src/Controller/CategoryController.php
Je valide pour l'instant, mais à voir comment tu t'y prendras avec la "refonte" dont on va parler demain

2024-01-11 20:25 UTC, mickaellambert commented on src/Controller/LanguageController.php
> +        $languages = $languageRepository->findAll();
Ici, t'es pas obligé de venir déclarer une variable dans le vide, tu peux directement mettre `$languageRepository->findAll();` dans ton return

2024-01-11 20:25 UTC, mickaellambert commented on src/Controller/LanguageController.php
> +         ]);
espace en trop juste avant le crochet

2024-01-11 20:25 UTC, mickaellambert commented on src/Controller/VideoController.php
> +    public function showAllVideosForOneCategory(
Ici, tu pourrais appeler ta fonction `listByCategory`, ce serait plus court et pas de méprise entre un show qui représente l'unicité et plusieurs vidéos

2024-01-11 20:25 UTC, mickaellambert commented on src/Controller/VideoController.php
> +    #[Route('/index/{slug}/{categoryLabel}', name: 'show_by_category')]
ici, tu devrais renommer le parametre slug en `languageSlug`, histoire qu'on comprenne bien que c'est pas celui de la vidéo par exemple
Et je suis pas fan du mot clé index devant ta route, ça marche pas si jamais tu la construis comme ça : `/{languageSlug}/{category}` ? Ca donnerait une route `/video/js/cours` par exemple

2024-01-11 20:25 UTC, mickaellambert commented on src/DataFixtures/CategoryFixtures.php
> +        LanguageFixtures::class,
elle était bien l'indentation avant haha

2024-01-11 20:25 UTC, mickaellambert commented on src/Entity/Category.php
> +
pas besoin de cette modif avec une ligne en +

2024-01-11 20:25 UTC, mickaellambert commented on src/Repository/VideoRepository.php
> +        $limit = abs($limit);
Je comprends pas trop l'intérêt du abs ici ?

2024-01-11 20:25 UTC, mickaellambert commented on src/Repository/VideoRepository.php
> +    public function findVideosByCategoryPaginated(int $page, string $category, int $limit = 9): array
tu peux renommer en `findByCategory` tout simplement, on comprendra que c'est des vidéos et qu'il y a de la pagination avec les parametres

2024-01-11 20:25 UTC, mickaellambert commented on src/Repository/VideoRepository.php
> -
elle était bien cette petite ligne ici

2024-01-11 20:25 UTC, mickaellambert commented on src/Repository/VideoRepository.php
> +        $query = $this->getEntityManager()->createQueryBuilder()
T'as suivi la documentation Symfony pour la pagination ?

2024-01-11 20:25 UTC, mickaellambert commented on symfony.lock
> -            "./config/packages/vich_uploader.yaml"
T'es sûr de cette modif ?

2024-01-11 20:25 UTC, mickaellambert commented on templates/base.html.twig
> +
pas besoin de cette ligne en +

2024-01-11 20:25 UTC, mickaellambert commented on templates/category/index.html.twig
> +	<div id="index-category">
Il y a pas un probleme d'indentation sur ce fichier ? J'ai l'impression qu'il y a 8 espaces au lieu de 4

2024-01-11 20:25 UTC, mickaellambert commented on webpack.config.js
> +    .autoProvidejQuery()
Du coup t'as besoin d'inclure jQuery en CDN en + de cette ligne ?

2024-01-12 08:41 UTC, ElieBendier commented on assets/cardHover.js
done

2024-01-12 08:42 UTC, ElieBendier commented on assets/carousel.js
> +document.addEventListener('DOMContentLoaded', function () {
done

2024-01-12 08:49 UTC, ElieBendier commented on assets/styles/_base.scss
> +
done.

2024-01-12 08:49 UTC, ElieBendier commented on assets/styles/_base.scss
> +
done

2024-01-12 08:52 UTC, ElieBendier commented on src/Repository/VideoRepository.php
> +        $query = $this->getEntityManager()->createQueryBuilder()
J'ai essayé de faire sans knppaginator qui apparemment est beaucoup utilisé, et j'ai suivi un tuto du coup qui utilise juste paginator.
La pagination fonctionne bien

2024-01-12 08:52 UTC, ElieBendier commented on templates/base.html.twig
> +
done

2024-01-12 08:54 UTC, ElieBendier commented on templates/category/index.html.twig
> +	<div id="index-category">
effectivement visuellement on dirait qu'il y en a 8 mais en local je n'en ai bien que 4. on verra si c'est réglé avec le prochain push.

2024-01-12 08:57 UTC, ElieBendier commented on webpack.config.js
> +    .autoProvidejQuery()
Effectivement tu as raison en fait je n'ai plus besoin de jQuery du tout, donc j'ai aussi supprimé l'inclusion en CDN

2024-01-12 09:00 UTC, ElieBendier commented on assets/styles/_navbar.scss
> +
done

2024-01-12 09:10 UTC, ElieBendier commented on assets/styles/_navbarMobile.scss
> -        z-index: 2;
done

2024-01-12 09:12 UTC, ElieBendier commented on config/packages/vich_uploader.yaml
> +        logo_file:
done

2024-01-12 09:12 UTC, ElieBendier commented on src/Controller/CategoryController.php
ça marche !

2024-01-12 09:16 UTC, ElieBendier commented on src/Controller/LanguageController.php
> +        $languages = $languageRepository->findAll();
done

2024-01-12 09:19 UTC, ElieBendier commented on src/Controller/LanguageController.php
> +         ]);
done

2024-01-12 09:20 UTC, ElieBendier commented on src/Controller/VideoController.php
> +    public function showAllVideosForOneCategory(
done

2024-01-12 09:31 UTC, ElieBendier commented on src/DataFixtures/CategoryFixtures.php
> +        LanguageFixtures::class,
mdr désolé !

2024-01-12 09:32 UTC, ElieBendier commented on src/Entity/Category.php
> +
done

2024-01-12 09:34 UTC, ElieBendier commented on src/Repository/VideoRepository.php
> +        $limit = abs($limit);
c'est pour être certain qu'aucune valeur négative ne soit rentrée et qu'on se retrouve à n'afficher aucune video ...

2024-01-12 09:35 UTC, ElieBendier commented on src/Repository/VideoRepository.php
> +    public function findVideosByCategoryPaginated(int $page, string $category, int $limit = 9): array
done

2024-01-12 09:43 UTC, ElieBendier commented on src/Repository/VideoRepository.php
> -
done

2024-01-12 10:10 UTC, ElieBendier commented on assets/styles/category/index.scss
> +#index-category {
j'ai refait l'indentation de tous les index

2024-01-12 10:10 UTC, ElieBendier commented on assets/styles/language/index.scss
> +                }
j'ai refait l'indentation de tous les index

2024-01-12 11:03 UTC, ElieBendier commented on src/Controller/VideoController.php
> +    #[Route('/index/{slug}/{categoryLabel}', name: 'show_by_category')]
c'est fait !

2024-01-12 11:06 UTC, ElieBendier commented on migrations/Version20231220112619.php
> +<?php
Done

2024-01-12 13:36 UTC, ElieBendier commented on assets/cardHover.js
> +if (window.innerWidth >= 768) {
done

2024-01-12 14:44 UTC, ElieBendier commented on config/packages/vich_uploader.yaml
> +        logo_file:
done

2024-01-12 14:44 UTC, ElieBendier commented on src/Repository/VideoRepository.php
> +    public function findVideosByCategoryPaginated(int $page, string $category, int $limit = 9): array
fait

2024-01-22 13:22 UTC, mickaellambert requested changes

2024-01-22 13:22 UTC, mickaellambert commented on assets/app.js
> +if (window.innerWidth >= 768) {
Déso

2024-01-22 13:22 UTC, mickaellambert commented on assets/cardHover.js
> +Array.from(indexCards).forEach(indexCard => {
indexCards.forEach()

2024-01-22 15:53 UTC, ElieBendier commented on assets/app.js
> +if (window.innerWidth >= 768) {
done

2024-01-22 16:06 UTC, ElieBendier commented on assets/cardHover.js
> +Array.from(indexCards).forEach(indexCard => {
JS c'est du caca

2024-01-23 11:56 UTC, mickaellambert approved these changes

2024-01-23 11:56 UTC, merged