S2 us23 dashboard
WildCodeSchool-2023-09/php-paris-p3-originsdigital pull request #12
Opened 2024-01-24 11:19 UTC by ArnoldMsl

2024-01-25 07:10 UTC, NicoDestephen approved these changes

2024-01-26 08:53 UTC, mickaellambert requested changes

2024-01-26 08:53 UTC, mickaellambert commented on assets/app.js
> +// require('bootstrap');
A decommenter et à retester

2024-01-26 08:53 UTC, mickaellambert commented on src/Controller/LoginController.php
> +        return $this->render('language/index.html.twig');
Plutôt que de faire un render, fais moi un redirect

2024-01-26 08:53 UTC, mickaellambert commented on src/Controller/UserController.php
> +            return $this->redirectToRoute('language_index', [], Response::HTTP_SEE_OTHER);
Soit à login direct, soit à rediriger vers le form de login

2024-01-26 10:11 UTC, ArnoldMsl commented on assets/app.js
> +// require('bootstrap');
il est réimporté ensuite, ça fonctionne : j'ai viré la ligne

2024-01-26 10:20 UTC, mickaellambert approved these changes

2024-01-26 10:20 UTC, merged