Restructuring modeling
WildCodeSchool-2023-09/php-paris-p3-originsdigital pull request #13
Opened 2024-01-24 13:24 UTC by ElieBendier

Category table doesn't exist anymore.
Category is now an element of the video entity.
I have made all the changes needed for our existing features to work with these changes, which include:
- index language
- index category
- index video
- player video
- new video

2024-01-26 10:17 UTC, mickaellambert requested changes

2024-01-26 10:17 UTC, mickaellambert commented on src/Controller/VideoController.php
> +        $video = $videoRepository->findOneBy(['slug' => $videoSlug]);
Récupérer par slug ET par langage

2024-01-26 10:17 UTC, mickaellambert commented on src/Entity/Video.php
> +    public const CATEGORIES = ['Cours' => 'Cours', 'Tutoriel' => 'Tutoriel', 'LiveCoding' => 'LiveCoding'];
```
public const CATEGORIES = [
    'Cours', 
    'Tutoriel', 
    'LiveCoding'
];
```

2024-01-26 10:17 UTC, mickaellambert commented on src/Controller/LanguageController.php
> +        $results = $videoRepository->findByLanguage($language);
`$categories = $videoRepository->findDistinctCategories($language); `

2024-01-26 10:17 UTC, mickaellambert commented on src/Controller/LanguageController.php
> +            'videos' => $videos,
'categories' => $categories

2024-01-26 10:17 UTC, mickaellambert commented on templates/category/index.html.twig
> +			{% for key, category in videos %}
`for category in categories`

2024-01-26 10:17 UTC, mickaellambert commented on templates/category/index.html.twig
> +					<h2>{{key}}</h2>
category

2024-01-30 08:51 UTC, ElieBendier commented on src/Controller/VideoController.php
> +        $video = $videoRepository->findOneBy(['slug' => $videoSlug]);
Fait.

2024-01-30 08:59 UTC, ElieBendier commented on src/Entity/Video.php
> +    public const CATEGORIES = ['Cours' => 'Cours', 'Tutoriel' => 'Tutoriel', 'LiveCoding' => 'LiveCoding'];
fait.

2024-01-30 14:07 UTC, ElieBendier commented on src/Controller/LanguageController.php
> +        $results = $videoRepository->findByLanguage($language);
fait

2024-01-30 14:07 UTC, ElieBendier commented on src/Controller/LanguageController.php
> +            'videos' => $videos,
fait.

2024-01-30 14:07 UTC, ElieBendier commented on templates/category/index.html.twig
> +			{% for key, category in videos %}
fait

2024-01-30 14:08 UTC, ElieBendier commented on templates/category/index.html.twig
> +					<h2>{{key}}</h2>
fait

2024-01-30 14:52 UTC, mickaellambert approved these changes

2024-01-30 14:52 UTC, merged