Prepaprod
WildCodeSchool-2023-09/php-paris-p3-originsdigital pull request #28
Opened 2024-02-17 07:51 UTC by NicoDestephen

2024-02-19 06:26 UTC, ArnoldMsl requested changes

2024-02-19 06:26 UTC, ArnoldMsl commented on config/packages/web_profiler.yaml
Yo ! tu peux laisser toolbar : true ? elle sera automatiquement passé en false quand on pushera sur le main :)

2024-02-19 06:26 UTC, ArnoldMsl commented on assets/styles/partials/_base.scss
tu peux enlever ça ? Il me semble que ça marchait pas

2024-03-08 08:31 UTC, NicoDestephen commented on config/packages/web_profiler.yaml
done

2024-03-08 08:40 UTC, ArnoldMsl approved these changes

2024-03-10 17:40 UTC, ElieBendier approved these changes

2024-03-11 09:10 UTC, merged