S1 us02 account creation
WildCodeSchool-2023-09/php-paris-p3-originsdigital pull request #5
Opened 2024-01-05 10:09 UTC by ArnoldMsl

2024-01-05 13:50 UTC, mickaellambert requested changes

2024-01-05 13:50 UTC, mickaellambert commented on assets/picturePreview.js
> +function createThumbnail(sFile) {
optimise ton code

2024-01-05 13:50 UTC, mickaellambert commented on assets/styles/app.scss
> +@import "new_user_form";
Donc tous les fichiers css sont en camelCase à part le tien ?

2024-01-05 13:50 UTC, mickaellambert commented on config/services.yaml
> +
pas besoin de l'espace en plus

2024-01-05 13:50 UTC, mickaellambert commented on src/Entity/User.php
> +<?php
Efface juste les commentaires inutiles

2024-01-05 13:50 UTC, mickaellambert commented on templates/user/_form.html.twig
> +        <input type="file"
Remplace moi ça par des form_row

2024-01-05 13:50 UTC, mickaellambert commented on src/Repository/UserRepository.php
> +//    /**
Commentaires inutiles

2024-01-07 17:26 UTC, mickaellambert requested changes

2024-01-07 17:26 UTC, mickaellambert commented on templates/user/_form.html_old.twig
Pas sur que ce fichier soit encore nécessaire !

2024-01-08 10:37 UTC, ElieBendier approved these changes

2024-01-08 14:45 UTC, mickaellambert approved these changes

2024-01-08 14:45 UTC, merged