S1 us12 video player
WildCodeSchool-2023-09/php-paris-p3-originsdigital pull request #6
Opened 2024-01-05 14:04 UTC by NicoDestephen

Create video player page :

- i can read : title and description and video link to the bdd
- css responsive

update css of nav bar to fit with the components of video player page

2024-01-07 17:32 UTC, mickaellambert requested changes

2024-01-07 17:32 UTC, mickaellambert commented on src/Controller/VideoController.php
> +        if (!$video) {
Etant donné que tu utilises ta vidéo plus haut pour avoir les vidéos recommandés, je pense qu'il faut mettre ce test plus haut dans ton code, sinon tu aras quand même une erreur si tu n'as pas de vidéo

2024-01-07 17:32 UTC, mickaellambert commented on src/Controller/VideoController.php
> +        foreach ($categoryVideos as $key => $categoryVideo) {
Ici, tu pourrais déporter la logique métier dans un service, c'est pas au role du controleur de récupérer les vidéos recommandés pour une vidéo ;)

2024-01-07 17:32 UTC, mickaellambert commented on src/Controller/VideoController.php
> +        return $this->render('video/index.html.twig', [
Essaie d'espacer un peu plus ton code entre tes blocs stp

2024-01-07 17:32 UTC, mickaellambert commented on src/DataFixtures/VideoFixtures.php
> +                    'title' => [
Probleme d'indentation la non ?

2024-01-07 17:32 UTC, mickaellambert commented on src/DataFixtures/VideoFixtures.php
> +        $videoData = [
L'organisation de tes données est pas hyper facile à comprendre, et ca me parait bizarre que ta boucle plus bas marche

Ce serait plus compréhensible si tu avais un tableau de vidéos et chaque vidéo étant un autre tableau avec comme clés les propriétés de cette derniere

2024-01-07 17:32 UTC, mickaellambert commented on templates/Video/index.html.twig
> +    {% for recommandedVideo in recommandedVideos %}
Si c'est un bloc qu'on retrouve plusieurs fois sur le site, autant le déporter dans un fichier component séparé et l'importer ici
Sinon tu peux laisser ça comme ça

2024-01-07 17:32 UTC, mickaellambert commented on templates/base.html.twig
> +		{% block nav %}
petit probleme d'indentation non ?

2024-01-08 13:28 UTC, ElieBendier approved these changes

2024-01-09 11:02 UTC, mickaellambert approved these changes

2024-01-09 11:02 UTC, merged